### ISSUE TITLE
haus-keeper: project email aliases

### ISSUE THREAD

**Issue by ebullient** [commonhaus/automation#144]
Use normal web UI

- [ ] Config file:
    ```yaml
    domain:
    user-team: (optional, for login@domain addresses)
    user-mapping: (in addition)
      - login:
        aliases: [] 
    ```
- [ ] New status 'CONTRIBUTOR' < 'SPONSOR'
  - [ ] Attestation: forward email T&C
- [ ] Read config files
  - [ ] Create stub files for users with email alias(es)
